Added data fetching feature to main page.
42masterplan/ft_transcendence pull request #54
Opened 2023-12-21 12:16 UTC by Honeybeei

## ✅ 풀\_리퀘스트 체크리스트

- [x] PR 제목: [Feature/Fix/Refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [x] commit message 가 적절한지 확인해주세요.
- [x] 적절한 branch 로 요청했는지 확인해주세요.
- [x] Assignees, Label 을 붙여주세요.
- [x] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer 로 등록해주세요.
- [ ] PR이 승인된 경우 해당 브랜치는 삭제해 주세요!

<br/>

## 🔄 변경 사항

Main page... 드디어 더미데이터에서 탈출 했습니다!!

- main page 에 접근 시 자신의 userName을 구해 /userInfo/[userName]으로 routing 시킵니다. (Routing : TODO)
- 한 덩어리였던 페이지를 섹션별로 분리 시키고 각각의 세션에서 data를 fetching합니다. 
- fetching 하는 데이터는 코멘트로 명시해 두었고 새로 구현이 필요한 (겹치기 쉬운) interface들은 components/sections/forDataFetching/interfaces.ts에 따로 구현했습니다. 

<br/>

## 📎 변경한 이유

- 언제까지 로컬 더미 데이터에 의존할 셈인가!!!!!

<br/>

TODO: 
1. Notion -> interface 수정
2. github issue -> mainpage dummy data 수정
3. .... 아 또 하나 뭐였지

closes: #Issue Number

## 👨🏻‍💻 테스트 체크리스트

- 이러한 테스트를 했어요!

<br/>

## 📌 변경 및 주의 사항

<br/>

2023-12-21 12:28 UTC, daejlee commented on components/sections/userInfoPage/forDataFetching/interfaces.ts
> +  player1Name: string;
player1 -> playerA
player2 -> playerB로 변경 가능한가여?
다른 코드들에서 플레이어 변수를 다 A, B 네이밍으로 선언한 상태라서 혹시 모를 호환 문제가 잇을까봐!!

2023-12-21 14:28 UTC, daejlee approved these changes
LGTM~~ 수고 많으셧읍니다

2023-12-22 03:40 UTC, Hawardshin requested changes
최고입니다~~ 각자 따로 로딩바를 둔게 더 마음에 드네요 최고에요~~
제 수정 요청사항 한번 확인 부탁드려요!!

2023-12-22 03:40 UTC, Hawardshin commented on components/sections/userInfoPage/AchievementSection.tsx
> +  }, [userName]);
여기서 조건문으로 if userName이 빈 경우 fetchData를 호출 안하게 하시는 건 어떨까요?
지금 보니까 처음 마운트 될때 한번 요청하고 userInfo state설정될 때 한번 더 호출 될 것 같아서요!

2023-12-22 03:40 UTC, Hawardshin commented on components/sections/userInfoPage/AchievementSection.tsx
> +          <SpinningLoader />
크으 따로따로 되는거 좋습니다!

2023-12-22 03:40 UTC, Hawardshin commented on components/sections/userInfoPage/GameStatsSection.tsx
> +  }, [userName]);
여기도 한번 조건문으로 userName빈 경우 처리 해주시면 좋을듯!

2023-12-22 03:40 UTC, Hawardshin commented on components/sections/userInfoPage/MatchHistorySection.tsx
> +      url: '/users/matches',
위의 내용과 동일해요!

2023-12-22 03:40 UTC, Hawardshin commented on pages/userInfo/[userName].tsx
> +    fetchData({
위와 동일입니당!

2023-12-22 03:40 UTC, Hawardshin commented on pages/userInfo/[userName].tsx
> +    }
앗 이거 훅에서 처음에 false로 돼있을 때 이러면 처음 랜더링 될 때 push가 될 것 같아요!!

2023-12-22 03:40 UTC, Hawardshin commented on pages/userInfo/[userName].tsx
> +    }
사용하실 때 훅에 error가 있어서 error is True이면 이걸 보내는 걸로 코드 수정하시면 될 것 같아요!

2023-12-23 07:48 UTC, Hawardshin approved these changes
좋아요~~ 고생하셨어요~~@!!!

2023-12-23 07:48 UTC, Hawardshin commented on pages/userInfo/[userName].tsx
> +    if (error !== null) {
=== true 일때 push하시면 됩니당~

2023-12-23 07:49 UTC, merged